/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class home_liqi_ndkdemo_NativeMethods */

#ifndef _Included_home_liqi_ndkdemo_NativeMethods
#define _Included_home_liqi_ndkdemo_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     home_liqi_ndkdemo_NativeMethods
 * Method:    printInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_liqi_ndkdemo_NativeMethods_printInfo
  (JNIEnv *, jclass);

/*
 * Class:     home_liqi_ndkdemo_NativeMethods
 * Method:    getStrings
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_home_liqi_ndkdemo_NativeMethods_getStrings
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
