/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class home_liqi_ndkdemo_NativeMethods */

#ifndef _Included_home_liqi_ndkdemo_NativeMethods
#define _Included_home_liqi_ndkdemo_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     home_liqi_ndkdemo_NativeMethods
 * Method:    printInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_liqi_ndkdemo_NativeMethods_printInfo
  (JNIEnv *env, jclass jobj){

    jobjectArray object_array;
    jint object_size;
    jobject obj = (*env)->FindClass(env, "home/liqi/ndkdemo/MainActivity");
//    object_size = (*env)->GetArrayLength(env,object_array);
//    jobject obj = (*env)->GetObjectArrayElement(env,object_array, 0);
    (*env)->DeleteLocalRef(env,obj);
   return (*env)->NewStringUTF(env,"aaaaaaa");



//    jclass objectClass = (env)->FindClass("com/sundy/jnidemo/DiskInfo");
}

/*
 * Class:     home_liqi_ndkdemo_NativeMethods
 * Method:    getStrings
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
//JNIEXPORT jobjectArray JNICALL Java_home_liqi_ndkdemo_NativeMethods_getStrings
//  (JNIEnv *env, jobject obj, jint count, jstring sample){
//
////    jobjectArray str_array ;
////    jclass cls_string;
////    jmethodID mid_string_init;
////    jobject obj_str;
////    const char *c_str_sample;
////    char buff[256];
////    int i;
////
////    // 保证至少可以创建3个局部引用（str_array，cls_string，obj_str）
////    if ((*env)->EnsureLocalCapacity(env, 3) != JNI_OK) {
////        return NULL;
////    }
////
////    c_str_sample = (*env)->GetStringUTFChars(env, sample, NULL);
////    if (c_str_sample == NULL) {
////        return NULL;
////    }
////
////    cls_string = (*env)->FindClass(env, "java/lang/String");
////    if (cls_string == NULL) {
////        return NULL;
////    }
////
////    // 获取String的构造方法
////    mid_string_init = (*env)->GetMethodID(env, cls_string, "<init>", "()V");
////    if (mid_string_init == NULL) {
////        (*env)->DeleteLocalRef(env,cls_string);
////        return NULL;
////    }
////    obj_str = (*env)->NewObject(env, cls_string, mid_string_init);
////    if (obj_str == NULL) {
////        (*env)->DeleteLocalRef(env,cls_string);
////        return NULL;
////    }
////
////    // 创建一个字符串数组
////    str_array = (*env)->NewObjectArray(env, count, cls_string, obj_str);
////    if (str_array == NULL) {
////        (*env)->DeleteLocalRef(env,cls_string);
////        (*env)->DeleteLocalRef(env,obj_str);
////        return NULL;
////    }
////
////    // 给数组中每个元素赋值
////    for (i = 0; i < count; ++i) {
////        memset(buff, 0, sizeof(buff));   // 初始一下缓冲区
////        sprintf(buff, c_str_sample,i);
////        jstring newStr = (*env)->NewStringUTF(env, buff);
////        (*env)->SetObjectArrayElement(env, str_array, i, newStr);
////    }
////
////    // 释放模板字符串所占的内存
////    (*env)->ReleaseStringUTFChars(env, sample, c_str_sample);
////
////    // 释放局部引用所占用的资源
////    (*env)->DeleteLocalRef(env, cls_string);
////    (*env)->DeleteLocalRef(env, obj_str);
//
//    return str_array;
//}
#ifdef __cplusplus
}
#endif
#endif